### ISSUE TITLE
使用yaml代替lisp表达式

### ISSUE THREAD

**Issue by Zacharia2** [Zacharia2/KCMS#41]
lisp本身就是可以转化为dict，json的方式，而且括号不好写，不如直接用yaml。

由我定义系统元数据。

**Comment by Zacharia2** [comment]
```yaml
ink pub:
  attr:
    type: Set
    p: [D, R]
```

**Comment by Zacharia2** [comment]
```yaml
ink.acc: pub
ink.attr.type: Set
ink.attr.p:
  - D
  - R
```
